---
driver:
  name: ec2
  region: us-east-1
  subnet_id: subnet-bbd17194
  security_group_ids:
  aws_ssh_key_id: virgina-key-pair
  tags:
    Owner: priyanka.elluri
    Environment: Testing
    Project: reandeploy
transport:
  ssh_key: /home/ec2-user/virgina-key-pair.pem
verifier:
  name: inspec
platforms:
  # Ubuntu trusty
  - name: ubuntu-14.04
    driver:
      instance_type: t2.micro
      tags:
        Name: web-page
suites:
  - name: default
    sudo: true
    run_list:
      - recipe[jenkins::default]
